esphome:
  name: "led-matrix-p5"
  friendly_name: 121 LED Matrix P5
  platformio_options:
        board_build.flash_mode: dio
external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.121
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LED Matrix P5"
    password: !secret ap_password

captive_portal:

i2c:
  sda: 41
  scl: 42

time:
  - platform: pcf8563
    address: 0x51
    id: pcf8563_time
  - platform: homeassistant
    on_time_sync:
      then:
        pcf8563.write_time:

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 12
  - file: 'Arial.ttf'
    id: arial
    size: 12
display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    R1_pin: 2
    R2_pin: 4
    G1_pin: 6
    G2_pin: 8
    B1_pin: 3
    B2_pin: 5
    A_pin: 39
    B_pin: 38
    C_pin: 37
    D_pin: 36
    E_pin: 12
    OE_pin: 35
    CLK_pin: 34
    LAT_pin: 33
    update_interval: 1s
    lambda: |-
      auto red = Color(255, 0, 0);
      auto blue = Color(0, 0, 255);
      auto rtc = id(pcf8563_time).now();
      it.line(1, 17, 0 + rtc.second, 17, blue);
      it.rectangle(0, 0, 64, 32, red);
      it.strftime(5, 2, id(roboto), " %H:%M:%S", rtc);
      if (id(custom_info).state.length() > 0) {
      // Print custom information (e.g., "Alarm State") in top center
      it.printf(2, 19, id(arial), "%s", id(custom_info).state.c_str());
      } else {
      if (id(temperature).has_state()) {
      it.printf(2, 19, id(arial),  "Temp:%.1f°C", id(temperature).state);
      }}
text_sensor:
  - platform: homeassistant
    name: "EspText"
    id: custom_info
    entity_id: input_text.custom_info
switch:
  - platform: hub75_matrix_display
    matrix_id: matrix
    restore_mode: ALWAYS_ON
    id: matrix_power
  - platform: gpio
    id: led_run
    pin: 40
sensor:
  - platform: homeassistant
    entity_id: sensor.bed_room_temperature
    id: temperature
    internal: true
    name: Matrix Temperature
  - platform: homeassistant
    entity_id: sensor.bed_room_humidity
    id: humidity
    name: Matrix Humidity
    internal: true
binary_sensor:
  - platform: gpio
    id: test_key
    pin:
      number: 11

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Brightness"